<?php

	add_action( 'widgets_init', 'register_wpl_exe_wp_logo_desc_widget' );
	
	function register_wpl_exe_wp_logo_desc_widget() {
		register_widget( 'wpl_exe_wp_logo_desc_widget' );
	}
	
	class wpl_exe_wp_logo_desc_widget extends WP_Widget {
		
		function __construct() {
			$widget_ops = array( 'classname' => 'wproto_logo_widget', 'description' => __('A widget that displays website logo and description.', 'wproto') );
		
			$control_ops = array( 'width' => 300, 'height' => 350, 'id_base' => 'wproto_logo_widget' );
		
			parent::__construct( 'wproto_logo_widget', __( '[EXE] Logo &amp; Description', 'wproto' ), $widget_ops, $control_ops );
		}
		
		function widget( $args, $instance ) {
			global $wpl_exe_wp;
			
			$data = array();
			$data['title'] = isset( $instance['title'] ) ? apply_filters( 'widget_title', $instance['title'] ) : '';
			
			$data['instance'] = $instance;
			$data['args'] = $args;

			$wpl_exe_wp->view->load_partial( 'widgets/logo_and_desc', $data );

		}
		
		function update( $new_instance, $old_instance ) {
			$instance = $old_instance;

			//Strip tags from title and name to remove HTML 
			$allowed_tags = wp_kses_allowed_html( 'post' );
			$instance['logo_url'] = wp_kses( $new_instance['logo_url'], $allowed_tags );
			$instance['logo_2x_url'] = isset( $new_instance['logo_2x_url'] ) ? wp_kses( $new_instance['logo_2x_url'], $allowed_tags ) : '';
			$instance['logo_width'] = absint( $new_instance['logo_width'] );
			$instance['description'] = wp_kses( $new_instance['description'], wp_kses_allowed_html( 'post' ) );
		
			return $instance;
		}
		
		function form( $instance ) {
			
			//Set up some default widget settings.
			$defaults = array(
				'logo_url' => '',
				'logo_2x_url' => '',
				'logo_width' => '',
				'description' => '',
			);
			
			$instance = wp_parse_args( (array) $instance, $defaults );
			
			?>
			<p>
				<label><?php _e('Logo URL', 'wproto'); ?></label>:<br/>
				<input type="text" style="width: 100%" id="<?php echo $this->get_field_id( 'logo_url' ); ?>" name="<?php echo $this->get_field_name( 'logo_url' ); ?>" value="<?php echo esc_attr( $instance['logo_url'] ); ?>" />
				<a href="javascript:;" data-url-input="#<?php echo $this->get_field_id( 'logo_url' ); ?>" class="button wproto-image-selector"><?php _e( 'Upload', 'wproto' ); ?></a> 
				<a href="javascript:;" data-url-input="#<?php echo $this->get_field_id( 'logo_url' ); ?>" class="button wproto-image-remover"><?php _e( 'Remove logo', 'wproto' ); ?></a>
			</p>
			<?php if( wpl_exe_wp_utils::is_retina_enabled() ): ?>
			<p>
				<label><?php _e('Logo URL for Retina Displays', 'wproto'); ?></label>:<br/>
				<input type="text" style="width: 100%" id="<?php echo $this->get_field_id( 'logo_2x_url' ); ?>" name="<?php echo $this->get_field_name( 'logo_2x_url' ); ?>" value="<?php echo esc_attr( $instance['logo_2x_url'] ); ?>" />
				<a href="javascript:;" data-url-input="#<?php echo $this->get_field_id( 'logo_2x_url' ); ?>" class="button wproto-image-selector"><?php _e( 'Upload', 'wproto' ); ?></a> 
				<a href="javascript:;" data-url-input="#<?php echo $this->get_field_id( 'logo_2x_url' ); ?>" class="button wproto-image-remover"><?php _e( 'Remove logo', 'wproto' ); ?></a>
			</p>
			<?php endif; ?>
			<p>
				<label><?php _e('Logo width', 'wproto'); ?></label>:<br/>
				<input type="number" name="<?php echo $this->get_field_name( 'logo_width' ); ?>" id="<?php echo $this->get_field_id( 'logo_width' ); ?>" value="<?php echo esc_attr( $instance['logo_width'] ); ?>" />
			</p>
			<p>
				<label for="<?php echo $this->get_field_id( 'description' ); ?>"><?php _e('Description text', 'wproto'); ?></label>:<br/>
				<textarea style="width: 100%; height: 140px;" name="<?php echo $this->get_field_name( 'description' ); ?>" id="<?php echo $this->get_field_id( 'description' ); ?>"><?php echo esc_textarea( $instance['description'] ); ?></textarea>
			</p>
			<?php
		}
		
	}