<?php if( $data['posts']->have_posts() ): ?>

	<?php
		$_uniqid = uniqid();
	?>

	<?php if( ! $data['ajax_load'] ): ?>
	<div id="wproto-posts-grid-id-<?php echo $_uniqid; ?>" class="wproto-posts-grid masonry-posts style-<?php echo esc_attr( $data['style'] ); ?>">
	<?php endif; ?>
			
	<?php $i=1; while( $data['posts']->have_posts() ): $data['posts']->the_post(); ?>

		<div class="item">
			<?php get_template_part('part', 'post_content'); ?>
		</div>

	<?php endwhile; ?>
	
	<?php if( ! $data['ajax_load'] ): ?>
	</div>
	<?php endif; ?>
	
	<?php if( (bool)$data['display_pagination'] && ! $data['ajax_load'] ): ?>
		<?php
			wpl_exe_wp_front::pagination( array(
				'pagination_style' => $data['pagination_style'],
				'custom_query' => $data['posts'],
				'ajax_target' => '#wproto-posts-grid-id-' . $_uniqid,
				'append_type' => 'masonry',
				'shortcode' => 'wproto_blog'
			), $data );
		?>
	<?php endif; ?>

<?php elseif( ! $data['ajax_load'] ): ?>

	<?php get_template_part('part', 'no_posts'); ?>

<?php endif;

// Run JS if VC front-end builder active
if( isset( $_GET['vc_editable'] ) && $_GET['vc_editable'] ):
?>
	<script>
		if( typeof( window.wprotoFrontCore ) !== 'undefined' ) {
			window.wprotoFrontCore.initMasonry();
			window.wprotoFrontCore.initPostsCarousels();
			window.wprotoFrontCore.initLightbox();
			
			setTimeout(function() { window.wprotoFrontCore.initMasonry(); }, 2000);
			
		}
	</script>
<?php endif;