<?php global $wpl_exe_wp; ?>
<div class="wrap" id="wproto-settings-screen">
	<div id="icon-themes" class="icon32"><br /></div>
	
	<h2 class="nav-tab-wrapper wproto-nav-tab-wrapper">
		<a class="nav-tab nav-tab-active"><?php _e( 'Custom modes', 'wproto'); ?></a>
	</h2>
	
	<form action="" id="wproto-settings-form" method="post">
	
		<input type="hidden" name="wproto_action" value="admin_settings-save" />
		<input type="hidden" name="wproto_setting_env" value="custom_modes" />
	
		<?php if( isset( $_GET['updated'] ) && $_GET['updated'] ): ?>
		<div class="updated">
			<p><?php _e('Settings were saved', 'wproto'); ?></p>
		</div>
		<?php endif; ?>
	
		<!--
	
			Coming Soon Mode
		
		-->
	
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Coming Soon Mode', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr>
					<th>
						<label><?php _e( 'Enable "Coming Soon" mode', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$coming_soon_enabled = $wpl_exe_wp->get_option( 'coming_soon_enabled', 'custom_modes' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $coming_soon_enabled, '.wproto-coming-soon-mode-settings', 'custom_modes', 'coming_soon_enabled'); ?>
						
						<p class="description"><?php _e( 'All pages of your website will be not available to visitors (except logged administrators) and search engines while coming soon mode is enabled.', 'wproto' ); ?></p>
						
					</td>
				</tr>
			</table>
			
			<div class="wproto-coming-soon-mode-settings"<?php echo ! $coming_soon_enabled ? ' style="display: none;"' : ''; ?>>
			
				<table class="form-table wproto-form-table">
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Basic settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Page content', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$coming_soon_page_text = $wpl_exe_wp->get_option( 'coming_soon_page_text', 'custom_modes' ); 
						?>
				
						<?php
							wp_editor(
  							$coming_soon_page_text,
  							'wproto-coming-soon-page-text',
  							array(
    							'media_buttons' => false,
    							'textarea_name' => 'custom_modes[coming_soon_page_text]',
   								'textarea_rows' => 4,
    							'tabindex' => 4,
									'teeny' => true,
									'quicktags' => false,
    							'tinymce' => array(
										'theme_advanced_buttons1' => 'bold, italic',
      							'theme_advanced_buttons2' => '',
      							'theme_advanced_buttons3' => '',
      							'theme_advanced_buttons4' => ''
    							)	
  							)
							);
						?>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Page footer text', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_footer_text = $wpl_exe_wp->get_option( 'coming_soon_footer_text', 'custom_modes' ); 
							?>
					
							<?php
								wp_editor(
	  							$coming_soon_footer_text,
	  							'wproto-coming-soon-footer-text',
	  							array(
	    							'media_buttons' => false,
	    							'textarea_name' => 'custom_modes[coming_soon_footer_text]',
	   								'textarea_rows' => 4,
	    							'tabindex' => 4,
										'teeny' => true,
										'quicktags' => false,
	    							'tinymce' => array(
											'theme_advanced_buttons1' => 'bold, italic',
	      							'theme_advanced_buttons2' => '',
	      							'theme_advanced_buttons3' => '',
	      							'theme_advanced_buttons4' => ''
	    							)	
	  							)
								);
							?>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'The planned opening date', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$site_opening_date = $wpl_exe_wp->get_option( 'site_opening_date', 'custom_modes' ); 
							?>
					
							<input data-date-format="dd M yy" type="text" class="text wproto-date-picker" name="custom_modes[site_opening_date]" value="<?php echo esc_attr( $site_opening_date ); ?>" />
							<p class="description"><?php _e( 'Day / Month / Year', 'wproto' ); ?></p>
						
						</td>
					</tr>
				</table>
			
				<table class="form-table wproto-form-table">
					<tr class="without-space">
						<td colspan="2"><h4 class="header"><?php _e('Style settings', 'wproto'); ?></h4></td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Coming soon page style', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_page_style = $wpl_exe_wp->get_option( 'coming_soon_page_style', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[coming_soon_page_style]">
								<option value="style_1"><?php _e('Default (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $coming_soon_page_style == 'style_2' ? 'selected="selected"' : ''; ?> value="style_2"><?php _e('Style 2 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $coming_soon_page_style == 'style_3' ? 'selected="selected"' : ''; ?> value="style_3"><?php _e('Style 3 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $coming_soon_page_style == 'style_4' ? 'selected="selected"' : ''; ?> value="style_4"><?php _e('Style 4 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $coming_soon_page_style == 'style_5' ? 'selected="selected"' : ''; ?> value="style_5"><?php _e('Style 4 (for white backgrounds)','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Custom background color', 'wproto' ); ?>:</label>
						</th>
						<td>
							
							<?php
								$coming_soon_page_bg_color = $wpl_exe_wp->get_option( 'coming_soon_page_bg_color', 'custom_modes' );
							?>
							
							<input class="wproto-color-picker" name="custom_modes[coming_soon_page_bg_color]" type="text" value="<?php echo esc_attr( $coming_soon_page_bg_color ); ?>">
							
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Background image', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_background = $wpl_exe_wp->get_option( 'coming_soon_background', 'custom_modes' ); 
							?>
					
							<input type="text" id="coming_soon_background" class="text" name="custom_modes[coming_soon_background]" value="<?php echo esc_attr( @$coming_soon_background ); ?>" /> <a href="javascript:;" class="button wproto-image-selector" data-url-input="#coming_soon_background"><?php _e( 'Upload', 'wproto' ); ?></a> 
							<a href="javascript:;" data-url-input="#coming_soon_background" class="button wproto-image-remover"><?php _e( 'Remove', 'wproto' ); ?></a></label>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Background repeat', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_background_repeat = $wpl_exe_wp->get_option( 'coming_soon_background_repeat', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[coming_soon_background_repeat]">
								<option value="repeat"><?php _e('Repeat horizontal and vertical','wproto'); ?></option>
								<option <?php echo $coming_soon_background_repeat == 'repeat-x' ? 'selected="selected"' : ''; ?> value="repeat-x"><?php _e('Horizontal repeat','wproto'); ?></option>
								<option <?php echo $coming_soon_background_repeat == 'repeat-y' ? 'selected="selected"' : ''; ?> value="repeat-y"><?php _e('Vertical repeat','wproto'); ?></option>
								<option <?php echo $coming_soon_background_repeat == 'no-repeat' ? 'selected="selected"' : ''; ?> value="no-repeat"><?php _e('No repeat','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Horizontal background position', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_background_h_pos = $wpl_exe_wp->get_option( 'coming_soon_background_h_pos', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[coming_soon_background_h_pos]">
								<option value="center"><?php _e('Center','wproto'); ?></option>
								<option <?php echo $coming_soon_background_h_pos == 'left' ? 'selected="selected"' : ''; ?> value="left"><?php _e('Left','wproto'); ?></option>
								<option <?php echo $coming_soon_background_h_pos == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e('Right','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Vertical background position', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_background_v_pos = $wpl_exe_wp->get_option( 'coming_soon_background_v_pos', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[coming_soon_background_v_pos]">
								<option value="center"><?php _e('Center','wproto'); ?></option>
								<option <?php echo $coming_soon_background_v_pos == 'top' ? 'selected="selected"' : ''; ?> value="top"><?php _e('Top','wproto'); ?></option>
								<option <?php echo $coming_soon_background_v_pos == 'bottom' ? 'selected="selected"' : ''; ?> value="bottom"><?php _e('Bottom','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Fixed background', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$coming_soon_background_fixed = $wpl_exe_wp->get_option( 'coming_soon_background_fixed', 'custom_modes' ); 
							?>
					
							<?php wpl_exe_wp_admin_utils::switcher( $coming_soon_background_fixed, false, 'custom_modes', 'coming_soon_background_fixed'); ?>

						
						</td>
					</tr>
				</table>
			
			</div>
		
		</div>
		
		<!--
	
			Maintenance Mode
		
		-->
	
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Maintenance mode', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr>
					<th>
						<label><?php _e( 'Enable "Maintenance" mode', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$maintenance_enabled = $wpl_exe_wp->get_option( 'maintenance_enabled', 'custom_modes' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $maintenance_enabled, '.wproto-maintenance-mode-settings', 'custom_modes', 'maintenance_enabled'); ?>
						
						<p class="description"><?php _e( 'All pages of your website will be not available to visitors and search engines while maintenance mode is enabled.', 'wproto' ); ?></p>
						
					</td>
				</tr>
			</table>
			
			<div class="wproto-maintenance-mode-settings"<?php echo ! $maintenance_enabled ? ' style="display: none;"' : ''; ?>>
			
				<table class="form-table wproto-form-table">
					<tr class="without-space">
						<td colspan="2"><h4 class="header"><?php _e('Basic settings', 'wproto'); ?></h4></td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Page content', 'wproto' ); ?>:</label>
						</th>
						<td>
						
							<?php
								$maintenance_page_text = $wpl_exe_wp->get_option( 'maintenance_page_text', 'custom_modes' ); 
							?>
					
							<?php
								wp_editor(
	  							$maintenance_page_text,
	  							'wproto-maintenance-page-text',
	  							array(
	    							'media_buttons' => false,
	    							'textarea_name' => 'custom_modes[maintenance_page_text]',
	   								'textarea_rows' => 4,
	    							'tabindex' => 4,
										'teeny' => true,
										'quicktags' => false,
	    							'tinymce' => array(
											'theme_advanced_buttons1' => 'bold, italic',
	      							'theme_advanced_buttons2' => '',
	      							'theme_advanced_buttons3' => '',
	      							'theme_advanced_buttons4' => ''
	    							)	
	  							)
								);
							?>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Page footer text', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_footer_text = $wpl_exe_wp->get_option( 'maintenance_footer_text', 'custom_modes' ); 
							?>
					
							<?php
								wp_editor(
	  							$maintenance_footer_text,
	  							'wproto-maintenance-footer-text',
	  							array(
	    							'media_buttons' => false,
	    							'textarea_name' => 'custom_modes[maintenance_footer_text]',
	   								'textarea_rows' => 4,
	    							'tabindex' => 4,
										'teeny' => true,
										'quicktags' => false,
	    							'tinymce' => array(
											'theme_advanced_buttons1' => 'bold, italic',
	      							'theme_advanced_buttons2' => '',
	      							'theme_advanced_buttons3' => '',
	      							'theme_advanced_buttons4' => ''
	    							)	
	  							)
								);
							?>
						
						</td>
					</tr>
				</table>
			
				<table class="form-table wproto-form-table">
					<tr class="without-space">
						<td colspan="2"><h4 class="header"><?php _e('Style settings', 'wproto'); ?></h4></td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Maintenance page style', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_page_style = $wpl_exe_wp->get_option( 'maintenance_page_style', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[maintenance_page_style]">
								<option value="style_1"><?php _e('Default (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $maintenance_page_style == 'style_2' ? 'selected="selected"' : ''; ?> value="style_2"><?php _e('Style 2 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $maintenance_page_style == 'style_3' ? 'selected="selected"' : ''; ?> value="style_3"><?php _e('Style 3 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $maintenance_page_style == 'style_4' ? 'selected="selected"' : ''; ?> value="style_4"><?php _e('Style 4 (for dark backgrounds)','wproto'); ?></option>
								<option <?php echo $maintenance_page_style == 'style_5' ? 'selected="selected"' : ''; ?> value="style_5"><?php _e('Style 4 (for white backgrounds)','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Custom background color', 'wproto' ); ?>:</label>
						</th>
						<td>
							
							<?php
								$maintenance_page_bg_color = $wpl_exe_wp->get_option( 'maintenance_page_bg_color', 'custom_modes' );
							?>
							
							<input class="wproto-color-picker" name="custom_modes[maintenance_page_bg_color]" type="text" value="<?php echo esc_attr( $maintenance_page_bg_color ); ?>">
							
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Background image', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_background = $wpl_exe_wp->get_option( 'maintenance_background', 'custom_modes' ); 
							?>
					
							<input type="text" id="maintenance_background" class="text" name="custom_modes[maintenance_background]" value="<?php echo esc_attr( @$maintenance_background ); ?>" /> <a href="javascript:;" class="button wproto-image-selector" data-url-input="#maintenance_background"><?php _e( 'Upload', 'wproto' ); ?></a> 
							<a href="javascript:;" data-url-input="#maintenance_background" class="button wproto-image-remover"><?php _e( 'Remove', 'wproto' ); ?></a></label>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Background repeat', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_background_repeat = $wpl_exe_wp->get_option( 'maintenance_background_repeat', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[maintenance_background_repeat]">
								<option value="repeat"><?php _e('Repeat horizontal and vertical','wproto'); ?></option>
								<option <?php echo $maintenance_background_repeat == 'repeat-x' ? 'selected="selected"' : ''; ?> value="repeat-x"><?php _e('Horizontal repeat','wproto'); ?></option>
								<option <?php echo $maintenance_background_repeat == 'repeat-y' ? 'selected="selected"' : ''; ?> value="repeat-y"><?php _e('Vertical repeat','wproto'); ?></option>
								<option <?php echo $maintenance_background_repeat == 'no-repeat' ? 'selected="selected"' : ''; ?> value="no-repeat"><?php _e('No repeat','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Horizontal background position', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_background_h_pos = $wpl_exe_wp->get_option( 'maintenance_background_h_pos', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[maintenance_background_h_pos]">
								<option value="center"><?php _e('Center','wproto'); ?></option>
								<option <?php echo $maintenance_background_h_pos == 'left' ? 'selected="selected"' : ''; ?> value="left"><?php _e('Left','wproto'); ?></option>
								<option <?php echo $maintenance_background_h_pos == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e('Right','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Vertical background position', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_background_v_pos = $wpl_exe_wp->get_option( 'maintenance_background_v_pos', 'custom_modes' ); 
							?>
					
							<select name="custom_modes[maintenance_background_v_pos]">
								<option value="center"><?php _e('Center','wproto'); ?></option>
								<option <?php echo $maintenance_background_v_pos == 'top' ? 'selected="selected"' : ''; ?> value="top"><?php _e('Top','wproto'); ?></option>
								<option <?php echo $maintenance_background_v_pos == 'bottom' ? 'selected="selected"' : ''; ?> value="bottom"><?php _e('Bottom','wproto'); ?></option>
							</select>
						
						</td>
					</tr>
					<tr>
						<th>
							<label><?php _e( 'Fixed background', 'wproto' ); ?>:</label>
						</th>
						<td>
					
							<?php
								$maintenance_background_fixed = $wpl_exe_wp->get_option( 'maintenance_background_fixed', 'custom_modes' ); 
							?>
					
							<?php wpl_exe_wp_admin_utils::switcher( $maintenance_background_fixed, false, 'custom_modes', 'maintenance_background_fixed'); ?>
						
						</td>
					</tr>
				</table>
			
			</div>
		
		</div>
		
		<!--
		
			Save button
			
		-->
		<div class="wproto-settings-box save-box">
			<input type="submit" name="wproto_reset_to_defaults" class="button alignleft" value="<?php _e( 'Reset to defaults', 'wproto' ); ?>" />
			<input type="submit" class="button button-primary" value="<?php _e( 'Save settings', 'wproto' ); ?>" />
		</div>
		
	</form>
	
</div>