<?php global $wpl_exe_wp, $wp_registered_sidebars; ?>
<div class="wrap" id="wproto-settings-screen">
	<div id="icon-themes" class="icon32"><br /></div>
	
	<h2 class="nav-tab-wrapper wproto-nav-tab-wrapper">
		<a class="nav-tab nav-tab-active"><?php _e( 'System layouts', 'wproto'); ?></a>
	</h2>
	
	<form action="" id="wproto-settings-form" method="post">
	
		<input type="hidden" name="wproto_action" value="admin_settings-save" />
		<input type="hidden" name="wproto_setting_env" value="system_layouts" />
		
		<?php if( isset( $_GET['updated'] ) && $_GET['updated'] ): ?>
		<div class="updated">
			<p><?php _e('Settings were saved', 'wproto'); ?></p>
		</div>
		<?php endif; ?>

		<!--
	
			Blog archive
		
		-->
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Blog archive', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr class="without-space noborder">
					<td colspan="2"><h4 class="header"><?php _e('Custom titles', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Blog title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_page_title = $wpl_exe_wp->get_option( 'blog_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[blog_page_title]" value="<?php echo esc_attr( $blog_page_title ); ?>" />
						
					</td>
				</tr>				
				<tr>
					<th>
						<label><?php _e( 'Archive page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_archive_page_title = $wpl_exe_wp->get_option( 'blog_archive_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[blog_archive_page_title]" value="<?php echo esc_attr( $blog_archive_page_title ); ?>" />
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Categories archive page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_cats_page_title = $wpl_exe_wp->get_option( 'blog_cats_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[blog_cats_page_title]" value="<?php echo esc_attr( $blog_cats_page_title ); ?>" />
						
						<p class="description"><?php _e('Use "%s" to display a category name from query', 'wproto'); ?></p>
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Tags archive page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_tags_page_title = $wpl_exe_wp->get_option( 'blog_tags_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[blog_tags_page_title]" value="<?php echo esc_attr( $blog_tags_page_title ); ?>" />
						
						<p class="description"><?php _e('Use "%s" to display a name of tag from query', 'wproto'); ?></p>
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( '"Read more" link custom text', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_read_more_text = $wpl_exe_wp->get_option( 'blog_read_more_text', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[blog_read_more_text]" value="<?php echo esc_attr( $blog_read_more_text ); ?>" />
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Layout', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Layout style', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_archive_layout = $wpl_exe_wp->get_option( 'blog_archive_layout', 'system_layouts' );
							$_blog_layouts = $wpl_exe_wp->system_config['blog_styles']; 
						?>
					
						<select class="select" name="system_layouts[blog_archive_layout]">
							<?php foreach( $_blog_layouts as $k=>$v ): ?>
							<option <?php echo $blog_archive_layout == $v ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $v ); ?>"><?php echo esc_html( $k ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Sidebar options', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display sidebar at blog archives page', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_archive_page_sidebar = $wpl_exe_wp->get_option( 'blog_archive_page_sidebar', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $blog_archive_page_sidebar, 'tr.blog-archive-sidebar-settings', 'system_layouts', 'blog_archive_page_sidebar'); ?>
						
					</td>
				</tr>
				<tr class="blog-archive-sidebar-settings"<?php echo $blog_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Blog archive sidebar position', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_archive_sidebar_position = $wpl_exe_wp->get_option( 'blog_archive_sidebar_position', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[blog_archive_sidebar_position]">
							<option value="left"><?php _e( 'Left', 'wproto' ); ?></option>
							<option <?php echo $blog_archive_sidebar_position == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e( 'Right', 'wproto' ); ?></option>
						</select>
						
					</td>
				</tr>
				<tr class="blog-archive-sidebar-settings"<?php echo $blog_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Blog archive widget area', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$blog_archive_widget_area = $wpl_exe_wp->get_option( 'blog_archive_widget_area', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[blog_archive_widget_area]">
							<?php foreach( $wp_registered_sidebars as $sidebar ): ?>
							<option <?php echo $blog_archive_widget_area == $sidebar['id'] ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $sidebar['id'] ); ?>"><?php echo esc_html( $sidebar['name'] ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
			</table>
		</div>
		
		<!--
	
			Portfolio archive
		
		-->
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Portfolio archive', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr class="without-space noborder">
					<td colspan="2"><h4 class="header"><?php _e('Custom titles', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( '"Read more" link custom text', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_read_more_text = $wpl_exe_wp->get_option( 'portfolio_read_more_text', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[portfolio_read_more_text]" value="<?php echo esc_attr( $portfolio_read_more_text ); ?>" />
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Portfolio category page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_cats_page_title = $wpl_exe_wp->get_option( 'portfolio_cats_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[portfolio_cats_page_title]" value="<?php echo esc_attr( $portfolio_cats_page_title ); ?>" />
						
						<p class="description"><?php _e('Use "%s" to display a category name from query', 'wproto'); ?></p>
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Layout', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Layout style', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_archive_layout = $wpl_exe_wp->get_option( 'portfolio_archive_layout', 'system_layouts' ); 
							$_portfolio_layouts = $wpl_exe_wp->system_config['portfolio_styles'];
						?>
					
						<select class="select" name="system_layouts[portfolio_archive_layout]">
							<?php foreach( $_portfolio_layouts as $k=>$v ): ?>
							<option <?php echo $portfolio_archive_layout == $v ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $v ); ?>"><?php echo esc_html( $k ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Sidebar settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display sidebar at portfolio archives page', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_archive_page_sidebar = $wpl_exe_wp->get_option( 'portfolio_archive_page_sidebar', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $portfolio_archive_page_sidebar, 'tr.portfolio-archive-sidebar-settings', 'system_layouts', 'portfolio_archive_page_sidebar'); ?>
						
					</td>
				</tr>
				<tr class="portfolio-archive-sidebar-settings"<?php echo $portfolio_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Portfolio archive sidebar position', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_archive_sidebar_position = $wpl_exe_wp->get_option( 'portfolio_archive_sidebar_position', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[portfolio_archive_sidebar_position]">
							<option value="left"><?php _e( 'Left', 'wproto' ); ?></option>
							<option <?php echo $portfolio_archive_sidebar_position == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e( 'Right', 'wproto' ); ?></option>
						</select>
						
					</td>
				</tr>
				<tr class="portfolio-archive-sidebar-settings"<?php echo $portfolio_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Portfolio archive widget area', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$portfolio_archive_widget_area = $wpl_exe_wp->get_option( 'portfolio_archive_widget_area', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[portfolio_archive_widget_area]">
							<?php foreach( $wp_registered_sidebars as $sidebar ): ?>
							<option <?php echo $portfolio_archive_widget_area == $sidebar['id'] ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $sidebar['id'] ); ?>"><?php echo esc_html( $sidebar['name'] ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
			</table>
		</div>
		
		<!--
	
			Author page
		
		-->
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Author\'s page', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr class="without-space noborder">
					<td colspan="2"><h4 class="header"><?php _e('Custom titles', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Author page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_page_display_info = $wpl_exe_wp->get_option( 'author_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[author_page_title]" value="<?php echo esc_attr( $author_page_display_info ); ?>" />
						
						<p class="description"><?php _e('Use "%s" to display author\'s name', 'wproto'); ?></p>
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( '"Read more" link custom text', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_read_more_text = $wpl_exe_wp->get_option( 'author_read_more_text', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[author_read_more_text]" value="<?php echo esc_attr( $author_read_more_text ); ?>" />
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Layout', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display information about author', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_page_display_info = $wpl_exe_wp->get_option( 'author_page_display_info', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $author_page_display_info, false, 'system_layouts', 'author_page_display_info'); ?>
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Layout style', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_archive_layout = $wpl_exe_wp->get_option( 'author_archive_layout', 'system_layouts' ); 
							$_blog_layouts = $wpl_exe_wp->system_config['blog_styles'];
						?>
					
						<select class="select" name="system_layouts[author_archive_layout]">
							<?php foreach( $_blog_layouts as $k=>$v ): ?>
							<option <?php echo $blog_archive_layout == $v ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $v ); ?>"><?php echo esc_html( $k ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>				
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Sidebar settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display sidebar at author\'s page', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_archive_page_sidebar = $wpl_exe_wp->get_option( 'author_archive_page_sidebar', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $author_archive_page_sidebar, 'tr.author-archive-sidebar-settings', 'system_layouts', 'author_archive_page_sidebar'); ?>
						
					</td>
				</tr>
				<tr class="author-archive-sidebar-settings"<?php echo $author_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Author\'s page archive sidebar position', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_archive_sidebar_position = $wpl_exe_wp->get_option( 'author_archive_sidebar_position', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[author_archive_sidebar_position]">
							<option value="left"><?php _e( 'Left', 'wproto' ); ?></option>
							<option <?php echo $author_archive_sidebar_position == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e( 'Right', 'wproto' ); ?></option>
						</select>
						
					</td>
				</tr>
				<tr class="author-archive-sidebar-settings"<?php echo $author_archive_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Author\'s page widget area', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$author_archive_widget_area = $wpl_exe_wp->get_option( 'author_archive_widget_area', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[author_archive_widget_area]">
							<?php foreach( $wp_registered_sidebars as $sidebar ): ?>
							<option <?php echo $author_archive_widget_area == $sidebar['id'] ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $sidebar['id'] ); ?>"><?php echo esc_html( $sidebar['name'] ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
			</table>
		</div>

		<!--
	
			Search layout
		
		-->
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Search page', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr class="without-space noborder">
					<td colspan="2"><h4 class="header"><?php _e('Custom titles', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Search results page title', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_results_page_title = $wpl_exe_wp->get_option( 'search_results_page_title', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[search_results_page_title]" value="<?php echo esc_attr( $search_results_page_title ); ?>" />
						
						<p class="description"><?php _e('Use "%s" to display a search query', 'wproto'); ?></p>
						
					</td>
				</tr>
				<tr>
					<th>
						<label><?php _e( '"Read more" link custom text', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_read_more_text = $wpl_exe_wp->get_option( 'search_read_more_text', 'system_layouts' ); 
						?>
					
						<input type="text" class="text" name="system_layouts[search_read_more_text]" value="<?php echo esc_attr( $search_read_more_text ); ?>" />
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Appearance settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Layout style', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_layout = $wpl_exe_wp->get_option( 'search_layout', 'system_layouts' ); 
							$_blog_layouts = $wpl_exe_wp->system_config['blog_styles'];
						?>
					
						<select class="select" name="system_layouts[search_layout]">
							<?php foreach( $_blog_layouts as $k=>$v ): ?>
							<option <?php echo $search_layout == $v ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $v ); ?>"><?php echo esc_html( $k ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>		
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Sidebar settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display sidebar at search results page', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_page_sidebar = $wpl_exe_wp->get_option( 'search_page_sidebar', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $search_page_sidebar, 'tr.search-page-sidebar-settings', 'system_layouts', 'search_page_sidebar'); ?>
						
					</td>
				</tr>
				<tr class="search-page-sidebar-settings"<?php echo $search_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Search page sidebar position', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_page_sidebar_position = $wpl_exe_wp->get_option( 'search_page_sidebar_position', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[search_page_sidebar_position]">
							<option value="left"><?php _e( 'Left', 'wproto' ); ?></option>
							<option <?php echo $search_page_sidebar_position == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e( 'Right', 'wproto' ); ?></option>
						</select>
						
					</td>
				</tr>
				<tr class="search-page-sidebar-settings"<?php echo $search_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Search page widget area', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$search_page_widget_area = $wpl_exe_wp->get_option( 'search_page_widget_area', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[search_page_widget_area]">
							<?php foreach( $wp_registered_sidebars as $sidebar ): ?>
							<option <?php echo $search_page_widget_area == $sidebar['id'] ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $sidebar['id'] ); ?>"><?php echo esc_html( $sidebar['name'] ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
			</table>
		
		</div>
		
		<!--
	
			404 layout
		
		-->
		<div class="wproto-settings-box">
			<h3 class="title"><?php _e( 'Page 404', 'wproto' ); ?></h3>
		
			<table class="form-table wproto-form-table">
				<tr>
					<th>
						<label><?php _e( 'Page content', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$e404_page_content = $wpl_exe_wp->get_option( 'e404_page_content', 'system_layouts' ); 
						?>
					
						<?php wp_editor( $e404_page_content, 'e404_page_content', array( 'teeny' => true, 'media_buttons' => false, 'textarea_rows' => 5, 'textarea_name' => 'system_layouts[e404_page_content]' ) ); ?>
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Appearance settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display search form', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$e404_show_search_form = $wpl_exe_wp->get_option( 'e404_show_search_form', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $e404_show_search_form, false, 'system_layouts', 'e404_show_search_form'); ?>
						
					</td>
				</tr>
				<tr class="without-space">
					<td colspan="2"><h4 class="header"><?php _e('Sidebar settings', 'wproto'); ?></h4></td>
				</tr>
				<tr>
					<th>
						<label><?php _e( 'Display sidebar at 404 page', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$e404_page_sidebar = $wpl_exe_wp->get_option( 'e404_page_sidebar', 'system_layouts' ); 
						?>
					
						<?php wpl_exe_wp_admin_utils::switcher( $e404_page_sidebar, 'tr.e404-page-sidebar-settings', 'system_layouts', 'e404_page_sidebar'); ?>
						
					</td>
				</tr>
				<tr class="e404-page-sidebar-settings"<?php echo $e404_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Search page sidebar position', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$e404_page_sidebar_position = $wpl_exe_wp->get_option( 'e404_page_sidebar_position', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[e404_page_sidebar_position]">
							<option value="left"><?php _e( 'Left', 'wproto' ); ?></option>
							<option <?php echo $e404_page_sidebar_position == 'right' ? 'selected="selected"' : ''; ?> value="right"><?php _e( 'Right', 'wproto' ); ?></option>
						</select>
						
					</td>
				</tr>
				<tr class="e404-page-sidebar-settings"<?php echo $e404_page_sidebar ? '' : ' style="display: none;"'; ?>>
					<th>
						<label><?php _e( 'Search page widget area', 'wproto' ); ?>:</label>
					</th>
					<td>
					
						<?php
							$e404_page_widget_area = $wpl_exe_wp->get_option( 'e404_page_widget_area', 'system_layouts' ); 
						?>
					
						<select class="select" name="system_layouts[e404_page_widget_area]">
							<?php foreach( $wp_registered_sidebars as $sidebar ): ?>
							<option <?php echo $e404_page_widget_area == $sidebar['id'] ? 'selected="selected"' : ''; ?> value="<?php echo esc_attr( $sidebar['id'] ); ?>"><?php echo esc_html( $sidebar['name'] ); ?></option>
							<?php endforeach; ?>
						</select>
						
					</td>
				</tr>
			</table>
		
		</div>
				
		<!--
		
			Save button
			
		-->
		<div class="wproto-settings-box save-box">
			<input type="submit" name="wproto_reset_to_defaults" class="button alignleft" value="<?php _e( 'Reset to defaults', 'wproto' ); ?>" />
			<input type="submit" class="button button-primary" value="<?php _e( 'Save settings', 'wproto' ); ?>" />
		</div>
		
	</form>
</div>