<table class="widefat" id="wproto-pricing-table-editor">
	<?php if( !is_array( $data['pricing_table'] ) || count( $data['pricing_table'] ) <= 0 ): ?>
	<thead>
		<tr>
			<th class="ex"><?php _e('Packages &amp; Features', 'wproto'); ?></th>
			<th class="package-title"><input name="pt[packages][names][0]" type="text" value="<?php _e('Basic', 'wproto'); ?>" /></th>
			<th class="package-title"><input name="pt[packages][names][1]" type="text" value="<?php _e('Pro', 'wproto'); ?>" /></th>
			<th class="package-title"><input name="pt[packages][names][2]" type="text" value="<?php _e('Unlimited', 'wproto'); ?>" /></th>
			<th class="ex"><a href="javascript:;" class="wproto-add-pricing-package button"><i class="fa fa-plus"></i> <?php _e('Add package', 'wproto'); ?></a></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th class="ex"><a href="javascript:;" class="wproto-add-pricing-feature button"><i class="fa fa-plus"></i> <?php _e('Add feature', 'wproto'); ?></a></th>
			<th class="center"><a href="javascript:;" title="<?php _e('Remove this plan', 'wproto'); ?>" class="wproto-delete-package button"><i class="fa fa-times"></i></a> <a href="javascript:;" title="<?php _e('Mark this plan as featured', 'wproto'); ?>" class="wproto-make-featured-price button"><i class="fa fa-star"></i><input type="radio" name="pt[pricing_table][featured]" value="0" /></a></th>
			<th class="center"><a href="javascript:;" title="<?php _e('Remove this plan', 'wproto'); ?>" class="wproto-delete-package button"><i class="fa fa-times"></i></a> <a href="javascript:;" title="<?php _e('Mark this plan as featured', 'wproto'); ?>" class="wproto-make-featured-price button button-primary"><i class="fa fa-star"></i><input type="radio" name="pt[pricing_table][featured]" checked="checked" value="1" /></a></th>
			<th class="center"><a href="javascript:;" title="<?php _e('Remove this plan', 'wproto'); ?>" class="wproto-delete-package button"><i class="fa fa-times"></i></a> <a href="javascript:;" title="<?php _e('Mark this plan as featured', 'wproto'); ?>" class="wproto-make-featured-price button"><i class="fa fa-star"></i><input type="radio" name="pt[pricing_table][featured]" value="2" /></a></th>
			<th class="ex"></th>
		</tr>
	</tfoot>
	<tbody>
		<tr class="move system-item item-price">
			<td class="description ex">
				<i><?php _e('Price', 'wproto'); ?></i>
			</td>
			<td><input name="pt[features][price][0][]" type="text" value="" /></td>
			<td><input name="pt[features][price][1][]" type="text" value="" /></td>
			<td><input name="pt[features][price][2][]" type="text" value="" /></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-currency">
			<td class="description ex">
				<i><?php _e('Price currency (e.g. $)', 'wproto'); ?></i>
			</td>
			<td><input name="pt[features][currency][0][]" type="text" value="" /></td>
			<td><input name="pt[features][currency][1][]" type="text" value="" /></td>
			<td><input name="pt[features][currency][2][]" type="text" value="" /></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-period">
			<td class="description ex">
				<i><?php _e('Time period (e.g. month / year etc.)', 'wproto'); ?></i>
			</td>
			<td><input name="pt[features][period][0][]" type="text" value="" /></td>
			<td><input name="pt[features][period][1][]" type="text" value="" /></td>
			<td><input name="pt[features][period][2][]" type="text" value="" /></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-details">
			<td class="description ex">
				<i><?php _e('Details', 'wproto'); ?></i>
			</td>
			<td><textarea name="pt[features][details][0][]"></textarea></td>
			<td><textarea name="pt[features][details][1][]"></textarea></td>
			<td><textarea name="pt[features][details][2][]"></textarea></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-rating">
			<td class="description ex">
				<i><?php _e('Star Rating (from 1 to 5)', 'wproto'); ?></i>
			</td>
			<td><input name="pt[features][rating][0][]" type="text" value="" /></td>
			<td><input name="pt[features][rating][1][]" type="text" value="" /></td>
			<td><input name="pt[features][rating][2][]" type="text" value="" /></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-icon">
			<td class="description ex">
				<i><?php _e('Package icon', 'wproto'); ?></i>
			</td>
			<td><i data-name="" class="wproto-icon-holder icon-2x"></i> <a href="javascript:;" class="wproto-icon-chooser"><?php _e('Select icon', 'wproto'); ?></a><input type="hidden" value="" name="pt[features][icon][0][]" class="wproto-icon-holder-input" /></td>
			<td><i data-name="" class="wproto-icon-holder icon-2x"></i> <a href="javascript:;" class="wproto-icon-chooser"><?php _e('Select icon', 'wproto'); ?></a><input type="hidden" value="" name="pt[features][icon][1][]" class="wproto-icon-holder-input" /></td>
			<td><i data-name="" class="wproto-icon-holder icon-2x"></i> <a href="javascript:;" class="wproto-icon-chooser"><?php _e('Select icon', 'wproto'); ?></a><input type="hidden" value="" name="pt[features][icon][2][]" class="wproto-icon-holder-input" /></td>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-button">
			<td class="description ex">
				<i><?php _e('Button text', 'wproto'); ?></i><br />
				<i><?php _e('Button URL', 'wproto'); ?></i>
			</td>
			<td>
				<input name="pt[features][button_text][0][]" type="text" value="" /><br />
				<input name="pt[features][button_url][0][]" type="text" value="" />
			</td>
			<td>
				<input name="pt[features][button_text][1][]" type="text" value="" /><br />
				<input name="pt[features][button_url][1][]" type="text" value="" />
			</td>
			<td>
				<input name="pt[features][button_text][2][]" type="text" value="" /><br />
				<input name="pt[features][button_url][2][]" type="text" value="" />
			</td>
			<td class="ex"></td>
		</tr>
		<tr class="move custom-item">
			<td class="description ex">
			
				<a href="javascript:;" title="<?php _e('Remove this feature', 'wproto'); ?>" class="button wproto-delete-feature"><i class="fa fa-times"></i></a>
			
				<input name="pt[features][user_features_names][0][]" type="text" value="<?php _e( 'Your feature', 'wproto'); ?>" />
			</td>
			<td><input name="pt[features][user_features_values][0][]" type="text" value="<?php _e( 'Basic value', 'wproto'); ?>" /></td>
			<td><input name="pt[features][user_features_values][1][]" type="text" value="<?php _e( 'Pro value', 'wproto'); ?>" /></td>
			<td><input name="pt[features][user_features_values][2][]" type="text" value="<?php _e( 'Unlimited value', 'wproto'); ?>" /></td>
			<td class="center ex"><img width="16" height="16" src="<?php echo WPROTO_THEME_URL . '/images/admin/'; ?>move@2x.png" alt="" /></td>
		</tr>
	</tbody>
	<?php else: ?>
	<thead>
		<tr>
			<th class="ex"><?php _e('Packages &amp; Features', 'wproto'); ?></th>
			<?php if( isset( $data['pricing_table']['packages']['names'] ) && is_array( $data['pricing_table']['packages']['names'] ) && count( $data['pricing_table']['packages']['names'] ) > 0 ): ?>
			
				<?php foreach( $data['pricing_table']['packages']['names'] as $k=>$v ): ?>
				<th class="package-title"><input name="pt[packages][names][<?php echo esc_attr( $k ); ?>]" type="text" value="<?php echo esc_attr( $v ); ?>" /></th>
				<?php endforeach; ?>
			
			<?php endif; ?>
			<th class="ex"><a href="javascript:;" class="wproto-add-pricing-package button"><i class="fa fa-plus"></i> <?php _e('Add package', 'wproto'); ?></a></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<th class="ex"><a href="javascript:;" class="wproto-add-pricing-feature button"><i class="fa fa-plus"></i> <?php _e('Add feature', 'wproto'); ?></a></th>
			<?php if( isset( $data['pricing_table']['packages']['names'] ) && is_array( $data['pricing_table']['packages']['names'] ) && count( $data['pricing_table']['packages']['names'] ) > 0 ): ?>
			
				<?php foreach( $data['pricing_table']['packages']['names'] as $k=>$v ): ?>
				
				<?php
					$featured = isset( $data['pricing_table']['pricing_table']['featured'] ) && ! is_array( $data['pricing_table']['pricing_table']['featured'] ) ? absint( $data['pricing_table']['pricing_table']['featured'] ) : -1;
				?>
				
				<th class="center"><a href="javascript:;" title="<?php _e('Remove this plan', 'wproto'); ?>" class="wproto-delete-package button"><i class="fa fa-times"></i></a> <a href="javascript:;" title="<?php _e('Mark this plan as featured', 'wproto'); ?>" class="wproto-make-featured-price button<?php echo $k == $featured ? ' button-primary' : ''; ?>"><i class="fa fa-star"></i><input type="radio" <?php echo $k == $featured ? 'checked="checked"' : ''; ?> name="pt[pricing_table][featured]" value="<?php echo esc_attr( $k ); ?>" /></a></th>
				<?php endforeach; ?>
			
			<?php endif; ?>
			<th class="ex"></th>
		</tr>
	</tfoot>
	<tbody>
		<tr class="move system-item item-price">
			<td class="description ex">
				<i><?php _e('Price', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td><input name="pt[features][price][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['price'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['price'][ $i ][0] ) : ''; ?>" /></td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-currency">
			<td class="description ex">
				<i><?php _e('Price currency (e.g. $)', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td><input name="pt[features][currency][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['currency'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['currency'][ $i ][0] ) : ''; ?>" /></td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-period">
			<td class="description ex">
				<i><?php _e('Time period (e.g. month / year etc.)', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td><input name="pt[features][period][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['period'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['period'][ $i ][0] ) : ''; ?>" /></td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-details">
			<td class="description ex">
				<i><?php _e('Details', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td><textarea name="pt[features][details][<?php echo $i; ?>][]"><?php echo isset($data['pricing_table']['features']['details'][ $i ][0]) ? esc_textarea( $data['pricing_table']['features']['details'][ $i ][0] ) : ''; ?></textarea></td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-price">
			<td class="description ex">
				<i><?php _e('Rating (from 1 to 5)', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td><input name="pt[features][rating][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['rating'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['rating'][ $i ][0] ) : ''; ?>" /></td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-icon">
			<td class="description ex">
				<i><?php _e('Package icon', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td>
				<?php echo isset($data['pricing_table']['features']['icon'][ $i ][0]) && $data['pricing_table']['features']['icon'][ $i ][0] <> '' ? '<i data-name="' . $data['pricing_table']['features']['icon'][ $i ][0] . '" class="wproto-icon-holder ' . $data['pricing_table']['features']['icon'][ $i ][0] . ' fa-4x"></i> <a href="javascript:;" class="wproto-icon-chooser">' . __( 'Change', 'wproto') . '</a>' : '<i data-name="" class="wproto-icon-holder icon-2x"></i> <a href="javascript:;" class="wproto-icon-chooser">' . __( 'Select icon', 'wproto') . '</a>'; ?>
				<input type="hidden" value="<?php echo isset($data['pricing_table']['features']['icon'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['icon'][ $i ][0] ) : ''; ?>" name="pt[features][icon][<?php echo $i; ?>][]" class="wproto-icon-holder-input" />
			</td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<tr class="move system-item item-button">
			<td class="description ex">
				<i><?php _e('Button text', 'wproto'); ?></i><br />
				<i><?php _e('Button URL', 'wproto'); ?></i>
			</td>
			<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
			<td>
				<input name="pt[features][button_text][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['button_text'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['button_text'][ $i ][0] ) : ''; ?>" /><br />
				<input name="pt[features][button_url][<?php echo $i; ?>][]" type="text" value="<?php echo isset($data['pricing_table']['features']['button_url'][ $i ][0]) ? esc_attr( $data['pricing_table']['features']['button_url'][ $i ][0] ) : ''; ?>" />
			</td>
			<?php endfor; ?>
			<td class="ex"></td>
		</tr>
		<?php if( isset( $data['pricing_table']['features']['user_features_names'] ) && count( $data['pricing_table']['features']['user_features_names'] ) ): ?>
		
			<?php foreach( $data['pricing_table']['features']['user_features_names'] as $k=>$v ): ?>
			
			<tr class="move custom-item">
				<td class="description ex">
			
					<a href="javascript:;" title="<?php _e('Remove this feature', 'wproto'); ?>" class="button wproto-delete-feature"><i class="fa fa-times"></i></a>
			
					<input name="pt[features][user_features_names][<?php $k; ?>][]" type="text" value="<?php echo isset( $v[0] ) ? esc_attr( $v[0] ) : ''; ?>" />
				</td>
				
				<?php for( $i=0; $i<count( $data['pricing_table']['packages']['names'] ); $i++ ): ?>
				<td><input name="pt[features][user_features_values][<?php echo $i; ?>][]" type="text" value="<?php echo isset( $data['pricing_table']['features']['user_features_values'][$i][$k] ) ? esc_attr( $data['pricing_table']['features']['user_features_values'][$i][$k] ) : ''; ?>" /></td>
				<?php endfor; ?>
				<td class="center ex"><img width="16" height="16" src="<?php echo WPROTO_THEME_URL . '/images/admin/'; ?>move@2x.png" alt="" /></td>
			</tr>
			
			<?php endforeach; ?>
		
		<?php endif; ?>
		
	</tbody>
	
	<?php endif; ?>
</table>