<?php
	$text_style = '';
	$bg_style = '';
	
	$text_style = $data['text_color'] <> '' ? 'color: ' . $data['text_color'] . '; ' : '';
	$bg_style = $data['bg_color'] <> '' ? 'background-color: ' . $data['bg_color'] . '; ' : '';
?>

<?php if( $data['header_text'] <> '' || $data['text'] ): ?>
<div class="wproto-call-to-action <?php echo $data['display_triangle'] ? 'with-triangle' : ''; ?> <?php if( $data['animation'] <> '' ): ?>wow <?php echo esc_attr( $data['animation'] ); ?><?php endif; ?> style-<?php echo esc_attr( $data['style'] ); ?>" <?php if( $data['animation'] <> '' ): ?>data-wow-delay="<?php echo esc_attr( $data['animation_delay'] ); ?>"<?php endif; ?> style="<?php echo esc_attr( $bg_style ); ?>">

	<div class="content-inner">
		<?php if( $data['header_text'] <> '' ): ?>
		<h2 style="<?php echo esc_attr( $text_style ); ?>"><?php echo esc_html( $data['header_text'] ); ?></h2>
		<?php endif; ?>
		
		<?php if( $data['text'] <> '' ): ?>
		<p style="<?php echo esc_attr( $text_style ); ?>"><?php echo wp_kses_post( $data['text'] ); ?></p>
		<?php endif; ?>
	</div>

	<div class="content-buttons">
		<?php if( $data['style'] != 'no-buttons' ): ?>
		
			<?php if( $data['button_text'] <> '' ): ?>
			<?php
				$link = ($data['button_link']=='||') ? '' : $data['button_link'];
				$link = function_exists('vc_build_link') ? vc_build_link($link) : $link;
				$a_href = $link['url'];
				$a_target = $link['target'];
			?>
			<a target="<?php echo esc_attr( $a_target ); ?>" href="<?php echo esc_attr( $a_href ); ?>" class="button button-style-black button-size-large"><?php echo esc_html( $data['button_text'] ); ?></a>
			<?php endif; ?>
			
			<?php if( $data['style'] == 'centered-2' && $data['button2_text'] <> '' ): ?>
			<?php
				$link = ($data['button2_link']=='||') ? '' : $data['button2_link'];
				$link = function_exists('vc_build_link') ? vc_build_link($link) : $link;
				$a_href = $link['url'];
				$a_target = $link['target'];
			?>
			<a target="<?php echo esc_attr( $a_target ); ?>" href="<?php echo esc_attr( $a_href ); ?>" class="button button-size-large button-style-black-stroke button-custom"><?php echo esc_html( $data['button2_text'] ); ?></a>
			<?php endif; ?>
		
		<?php endif; ?>
	</div>
	<div class="clearfix"></div>
</div>
<?php endif; 