<?php if( $data['posts']->have_posts() ): ?>

<div class="wproto-intro-posts">

	<?php if( $data['title'] <> '' ): ?>
	<div class="wproto-posts-carousel-block-title">
		<?php if( $data['display_read_all'] && $data['read_all_text'] <> '' ): ?>
		<a class="read-all" href="<?php echo $data['post_type'] == 'post' ? get_permalink( get_option('page_for_posts' ) ) : get_post_type_archive_link( $data['post_type'] ); ?>"><?php echo $data['read_all_text']; ?></a>
		<?php endif; ?>
		<h2><?php echo wp_kses_post( $data['title'] ); ?></h2>
	</div>
	<?php endif; ?>

	<?php $i=0; while( $data['posts']->have_posts() ): $data['posts']->the_post(); ?>
	<div class="item num-<?php echo $i; ?>">
		<div class="post-grid-media-header">
			<div class="post-thumbnail wproto-post-image-area">
				<?php echo wpl_exe_image( wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ) ), 390, 250 ); ?>
				<div class="overlay">
					<div class="overlay-inner">				
						<div class="buttons">
							<a class="lightbox zoom" href="<?php echo wp_get_attachment_url( get_post_thumbnail_id() ); ?>"><span class="hover_pulse_ray"></span></a>
							<a class="post-link" href="<?php the_permalink(); ?>"><span class="hover_pulse_ray"></span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="item-description">
			<div class="cats"><div class="date"><?php the_time( get_option('date_format')); ?> /</div> <?php echo wpl_exe_wp_front::get_categories(); ?></div>
			<h4 class="post-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h4>
			<div class="excerpt">
				<?php echo wp_trim_words( get_the_excerpt(), 18, '...'); ?>
			</div>
			<?php if( $data['read_more_text'] <> '' ): ?>
			<a class="more" href="<?php the_permalink(); ?>"><?php echo esc_html( $data['read_more_text'] ); ?></a>
			<?php endif; ?>
		</div>
	</div>
	<?php $i++; endwhile; ?>
	<div class="clearfix"></div>
</div>

<?php endif; 

// Run JS if VC front-end builder active
if( isset( $_GET['vc_editable'] ) && $_GET['vc_editable'] ):
?>
	<script>
		if( typeof( window.wprotoFrontCore ) !== 'undefined' ) {
			window.wprotoFrontCore.initLightbox();
		}
	</script>
<?php endif;