<div class="wproto-shortcode-partners-clients">

	<?php if( $data['posts']->have_posts() ): ?>
	<!-- logos carousel -->
	<div class="items" data-autoplay-speed="<?php echo $data['autoplay'] ? esc_attr( $data['autoplay_speed'] ) : '0'; ?>" data-display-nav="<?php echo esc_attr( $data['nav'] ); ?>" data-items="<?php echo absint( $data['items'] ) > 0 ? $data['items'] : 1; ?>">

		<?php while( $data['posts']->have_posts() ): $data['posts']->the_post(); ?>

			<?php $url = get_post_meta( get_the_ID(), 'url', true ); ?>

			<div class="item">
				<div class="inside">
					<?php $image = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID() ), 'full' ); ?>
					
					<a href="<?php echo $url <> '' ? esc_attr( $url ) : 'javascript:;'; ?>" rel="nofollow" target="<?php echo esc_attr( $data['target'] ); ?>"><img src="<?php echo $image[0]; ?>" alt="" /></a>
					
					<?php if( $data['display_title'] ): ?>
					<a href="<?php echo $url <> '' ? esc_attr( $url ) : 'javascript:;'; ?>" class="pc-title" rel="nofollow" target="<?php echo esc_attr( $data['target'] ); ?>"><?php the_title(); ?></a>
					<?php endif; ?>
					
				</div>
			</div>
	
		<?php endwhile; wp_reset_postdata(); ?>
					
	</div>
	<?php endif; ?>
</div>

<?php
// Run JS if VC front-end builder active
if( isset( $_GET['vc_editable'] ) && $_GET['vc_editable'] ):
?>
	<script>
		if( typeof( window.wprotoFrontCore ) !== 'undefined' ) {
			window.wprotoFrontCore.initCarousels();
		}
	</script>
<?php endif;