<?php global $woocommerce; if( $data['posts']->have_posts() ): ?>

	<div class="wproto-products-list">

	<?php if( $data['title'] <> '' ): ?>
	<h4 class="shortcode-title"><?php echo esc_html( $data['title'] ); ?></h4>
	<?php endif; ?>

	<div class="items">
	<?php while( $data['posts']->have_posts() ): $data['posts']->the_post(); ?>
	
		<?php
			$product = wc_get_product( get_the_ID() );
			$img_url = wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ) );
		?>
	
		<div class="item <?php echo has_post_thumbnail( get_the_ID() ) ? 'with-thumb' : 'no-thumb'; ?>">
			
			<div class="thumb">
				<a href="<?php the_permalink(); ?>">
					<?php echo wpl_exe_image( $img_url, 54, 70 ); ?>
				</a>
			</div>
			
			<div class="desc">
				<div class="product-rating">
					<?php echo $product->get_rating_html(); ?>
				</div>
				<a href="<?php the_permalink(); ?>" class="title"><?php the_title(); ?></a>
				<div class="product-price">
					<?php echo $product->get_price_html(); ?>
				</div>
			</div>
			
		</div>
	
	<?php endwhile; ?>
	</div>
	
	</div>

<?php endif;