<?php
	global $wpl_exe_wp;

	switch( $data['instance']['query_type'] ) {
		default:
		case('recent'):
			$posts = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'date', 'DESC', $data['instance']['post_type'], '', false, false, false );
		break;
		case('featured'):
			$posts = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'date', 'DESC', $data['instance']['post_type'], '', true, false, false );
		break;
		case('most_commented'):
			$posts = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'comment_count', 'DESC', $data['instance']['post_type'], '', false, false, false );
		break;
		case('random'):
			$posts = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'rand', 'DESC', $data['instance']['post_type'], '', false, false, false );
		break;
		case('tabs'):
			$posts = array();
			$posts['recent'] = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'date', 'DESC', $data['instance']['post_type'], '', false, false, false );
			$posts['popular'] = $wpl_exe_wp->model('post')->get( 'all', $data['instance']['count'], '', 'comment_count', 'DESC', $data['instance']['post_type'], '', false, false, false );
		break;
	}

?>

<?php echo $data['args']['before_widget']; ?>

<!-- widget title -->
<?php if ( isset( $data['title'] ) && $data['title'] <> '' ) : ?>

	<?php echo $data['args']['before_title']; ?>
	
		<?php echo apply_filters( 'widget_title', $data['title'] ); ?>
		
	<?php echo $data['args']['after_title']; ?>
	
<?php endif; ?>

<!-- widget content -->
<?php if( $data['instance']['query_type'] == 'tabs' ): ?>

	<div class="post-items-tabs">
	
		<?php $uniqid = uniqid(); ?>
		<ul class="nav nav-tabs">
			<li><a class="active" href="#wproto-recent-posts-tab-<?php echo $uniqid; ?>"><?php _e('Recent', 'wproto'); ?></a></li>
			<li><a href="#wproto-popular-posts-tab-<?php echo $uniqid; ?>"><?php _e('Popular', 'wproto'); ?></a></li>
		</ul>
		<div class="clearfix"></div>
		
		<div class="tab-content">
		
			<?php $i=0; foreach( $posts as $k=>$v ): $i++; ?>
			<div id="<?php echo $i == 1 ? 'wproto-recent-posts-tab-' : 'wproto-popular-posts-tab-'; ?><?php echo $uniqid; ?>" class="widget-tab <?php if( $i == 1 ): ?>active<?php endif; ?>">
			
				<div class="posts-items">
					<?php while( $v->have_posts() ): $v->the_post(); $with_thumb = has_post_thumbnail() && $data['instance']['display_thumbnails']; ?>
					
					<div class="item <?php echo $with_thumb ? 'with-thumbnail' : 'without-thumbnail'; ?>">
					
						<?php if( $with_thumb ): ?>
						
							<div class="thumb">
								<a class="lightbox" href="<?php echo wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ), 'full' ); ?>">
									<?php echo wpl_exe_image( wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ) ), 70, 70 ); ?>
									<div class="bg"></div>
									<div class="hover_icon">
										<div class="hover_pulse_ray"></div>
									</div>
								</a>
							</div>
						
						<?php endif; ?>
						
						<?php if( !$data['instance']['display_thumbnails'] ): ?>
						<div class="post-date">
							<span class="day"><?php the_time( 'd' ); ?></span>
							<span class="month"><?php the_time( 'M' ); ?></span>
						</div>
						<?php endif; ?>
					
						<div class="excerpt">
						
							<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
							
							<?php if( !$data['instance']['display_thumbnails'] ): ?>
								<div class="comments-number">
									<?php comments_number( __('no comments', 'wproto'), __('one comment', 'wproto'), __('<span class="comments-num">%</span> comments', 'wproto') ); ?>.
								</div>
							<?php else: ?>
								<p><time datetime="<?php the_time('Y-m-d'); ?>"><?php the_time( get_option('date_format')); ?></time></p>
							<?php endif; ?>
						
						</div>
					
					</div>
					<?php endwhile; wp_reset_postdata(); ?>
				</div>
			
			</div>
			<?php endforeach; ?>
		
		</div>
	
	</div>

<?php else: ?>

	<div class="posts-items style-<?php echo $data['instance']['query_type']; ?> thumbs-<?php echo $data['instance']['display_thumbnails'] ? 'on' : 'off'; ?>">
		<?php while( $posts->have_posts() ): $posts->the_post(); $with_thumb = has_post_thumbnail() && $data['instance']['display_thumbnails']; ?>
		
		<div class="item <?php echo $with_thumb ? 'with-thumbnail' : 'without-thumbnail'; ?>">
		
			<?php if( $with_thumb ): ?>
			
				<div class="thumb">
					<a class="lightbox" href="<?php echo wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ), 'full' ); ?>">
						<?php echo wpl_exe_image( wp_get_attachment_url( get_post_thumbnail_id( get_the_ID() ) ), 70, 70 ); ?>
						<div class="bg"></div>
						<div class="hover_icon">
							<div class="hover_pulse_ray"></div>
						</div>
					</a>
				</div>
			
			<?php endif; ?>
			
			<?php if( !$data['instance']['display_thumbnails'] ): ?>
			<div class="post-date">
				<span class="day"><?php the_time( 'd' ); ?></span>
				<span class="month"><?php the_time( 'M' ); ?></span>
			</div>
			<?php endif; ?>
		
			<div class="excerpt">
			
				<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
				
				<?php if( !$data['instance']['display_thumbnails'] ): ?>
					<div class="comments-number">
						<?php comments_number( __('no comments', 'wproto'), __('one comment', 'wproto'), __('<span class="comments-num">%</span> comments', 'wproto') ); ?>.
					</div>
				<?php else: ?>
					<p><time datetime="<?php the_time('Y-m-d'); ?>"><?php the_time( get_option('date_format')); ?></time></p>
				<?php endif; ?>
			
			</div>
		
		</div>
		<?php endwhile; wp_reset_postdata(); ?>
	</div>
<?php endif; ?>

<?php echo $data['args']['after_widget']; 