<h3><?php _e( 'Add Items', 'wproto' ); ?>:</h3>

<div id="wproto-toggles-style-container">
	<p>
		<label><?php _e( 'Toggles Style', 'wproto' ); ?>:  <br />
		<select id="wproto-toggles-style-widget" style="width: 100%">
			<option value="style_9"><?php _e('Light style', 'wproto'); ?></option>
			<option value="style_11"><?php _e('Dark style', 'wproto'); ?></option>
		</select>
	</p>
</div>

<div id="wproto-toggles-tabs-items">

	<div class="item">
		
		<p>
			<label><?php _e( 'Title', 'wproto' ); ?>:  <br />
			<input class="wproto-toggles-tabs-title full-width-input" type="text" /> </label>
		</p>
		
		<p>
			<label><?php _e( 'Content', 'wproto' ); ?>:  <br />
			<textarea class="wproto-toggles-tabs-content full-width-textarea" style="height: 130px"></textarea> </label>
		</p>
		
		<div class="controls">
			<a href="javascript:;" class="remove"></a>
			<a href="javascript:;" class="add"></a>
		</div>
		
	</div>

</div>